# Generated by Django 5.2.4 on 2025-07-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geofencing_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
