# Generated by Django 5.2.4 on 2025-07-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodtracker',
            name='mood',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
